apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fld3hu9bs-go
  janus-idp.io/tekton: fld3hu9bs-go
  backstage.io/kubernetes-id: fld3hu9bs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fld3hu9bs-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
